version: "2"
volumes:
  database:
services:
  dimepi:
    build: .
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/mem"
      - "/dev/gpiomem"
    environment:
      - UDEV=1
    labels:
      io.balena.features.kernel-modules: '1'
    volumes:
      - database:/var/lib/dimepi
  sonos-api:
    image: chrisns/docker-node-sonos-http-api
    ports:
      - "5005:5005"
    network_mode: "host"
  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    network_mode: "host"
    environment:
      SQLITE_DATABASE: "/var/lib/dimepi/database.db"
    volumes:
      - database:/var/lib/dimepi